all: main

main: main.cpp normal_smithing_stone.h normal_weapon.h smithing_stone.cpp smithing_stone.h tarnished.cpp tarnished.h weapon.cpp weapon.h
	g++ main.cpp smithing_stone.cpp tarnished.cpp weapon.cpp -o main